### ISSUE TITLE
Support GNU make 3.81 (Darwin)

### ISSUE THREAD

**Issue by jrk** [alexreinking/halide-project-tool#7]

**Comment by alexreinking** [comment]
@jrk - I should have fixed the dylib vs so issue and removed the file function use. Not sure what to replace that with for MinGW, but at least it should work on your Mac now. Let me know if it does and I can close the issue.

**Comment by alexreinking** [comment]
Also, for reference, I needed the following patch to build Make 3.81 with GCC 8.3 in `glob/glob.c`

```
--- glob.c	2019-06-13 17:09:50.160182147 -0700
+++ glob.patched.c	2019-06-13 17:09:28.777044062 -0700
@@ -207,9 +207,9 @@
 #endif /* __GNU_LIBRARY__ */
 
 
-#if !defined __alloca && !defined __GNU_LIBRARY__
+#if 1 // !defined __alloca && !defined __GNU_LIBRARY__
 
-# ifdef	__GNUC__
+# if 1 // ifdef	__GNUC__
 #  undef alloca
 #  define alloca(n)	__builtin_alloca (n)
 # else	/* Not GCC.  */
```

Available here: [alloca.patch.txt](https://github.com/alexreinking/halide-project-tool/files/3288527/alloca.patch.txt)

**Comment by alexreinking** [comment]
It might also be worthwhile to upgrade your own make to 4.x via Homebrew. See the instructions here: https://apple.stackexchange.com/questions/261918/how-to-upgrade-gnu-make-in-os-x-el-capitan
